### ISSUE TITLE
Need of Enzyme

### ISSUE THREAD

**Issue by saurabh-dk** [tuantvk/WtfReactNativeTesting#5]
Thanks for the demo. Really helpful for the beginners. One thing I saw while reading react-native-testing-library docs is, it states that it is a replacement for Enzyme [here](https://callstack.github.io/react-native-testing-library/docs/getting-started#this-solution). 

So do we really need to add Enzyme to replicate your tutorial? I haven't actually started to write my tests yet.

**Comment by tuantvk** [comment]
@saurabhDuzumaki thanks for issue. I'll update docs in next time.

**Comment by tuantvk** [comment]
@saurabhDuzumaki new docs for testing use enzyme [Enzyme Members Testing](https://github.com/tuantvk/WtfReactNativeTesting#enzyme-members-testing) check it and report new issues for me. Thanks!
